### ISSUE TITLE
Game crashing with mod

### ISSUE THREAD

**Issue by PlayerCake** [Sheights/StarboundSimpleVoreMod#101]
Don't know if this has already been up or solved or anything, I read a few of the other issue logs and couldn't find it.  I have the mod version 8.3 and it works fine, there's no problems with it...  However any newer version doesn't work.  I've tried every release since then and it closes the game before it even gets to the main title screen.  I don't know if it's my computer or if I'm just doing something wrong with installing it, but it won't work.

**Comment by thetechnodragon** [comment]
did you try 9.0.0C? also the reason why 8.6.0 crashes has been found and fixed in 8.6.1, it was an issue with the metadata file that causes the game to not even hit the chucklefish logo, just to throw a error. 8.6.1 is the most up to date version.

**Comment by PlayerCake** [comment]
I put this up after just having tried the latest one they put up here, so yeah 8.6.1

**Comment by thetechnodragon** [comment]
alright, can you pastebin post the error log and plop the link in here, would help to see what's actually crashing.

**Comment by PlayerCake** [comment]
Ah...  I'm dumb sorry.  For whatever reason is was creating extra layers of folders and that was messing it up.  I got it working now, sorry for the disruption.
