### ISSUE TITLE
Lynn doesn't release you.

### ISSUE THREAD

**Issue by MonochromeDreams** [Sheights/StarboundSimpleVoreMod#109]
Using SSVM 8.6.1
If you let her animation get farther than it's first phase you're permanently stuck inside her, if you let the animation play through she does not release you, and the "eaten" buff/debuff ticks but immediately resets itself and you cannot request her to release you.
Also if you teleport, suicide, or exit the game while unbirthed, it has a chance to corrupt that world or you spawn invisible and unable to move.

**Comment by ArgobargSoup** [comment]
I have discovered that apparently, during the big NPC system rewrite, the code that was supposed to lower the compression timer got removed.
