### ISSUE TITLE
Lynn

### ISSUE THREAD

**Issue by Eclipse8264** [Sheights/StarboundSimpleVoreMod#133]
Lynn needs a look at. after you start to deform in her, there is no way out. i stay and long time in her and could never get out, not til i sent her away.

this may have something to do with the eaten time not going down, but all i know is i can't get out, and i'm not being let out.

**Comment by Screemonster** [comment]
You have to wriggle repeatedly to get out. Also you can just search "lynn" on the issue tracker to see this has been reported, and answered, many times before. The behaviour is intended.

**Comment by ArgobargSoup** [comment]
I have discovered that apparently, during the big NPC system rewrite, the code that was supposed to lower the compression timer got removed.  So this is actually a bug.
