### ISSUE TITLE
Game crashes almost as soon as it opens.

### ISSUE THREAD

**Issue by NetGlitched** [Sheights/StarboundSimpleVoreMod#158]
[starbound.log](https://github.com/Sheights/StarboundSimpleVoreMod/files/2934690/starbound.log)

Normally I would try to glance through the log myself even though I'm not good at it to try and figure out what's wrong, but the way starbound handles logs just leaves me confused and overwhelmed as soon as I open the file.

**Comment by Deadmanovi4** [comment]
[22:07:36.240] [Error] Application: exception thrown, shutting down: (StarException) Asset source 'OresForAsteroids' is missing dependency 'FrackinUniverse'
Try to disable mod Ores For Asteroind and try again

**Comment by NetGlitched** [comment]
Still crashes but it takes a bit longer now before it does. (My mod setup is just completely screwed up so i'm honestly not surprised) Got the new log.
[starbound.log](https://github.com/Sheights/StarboundSimpleVoreMod/files/2938940/starbound.log)

**Comment by Deadmanovi4** [comment]
> [16:52:24.174] [Error] Application: exception thrown, shutting down: (StarException) Asset source 'Elithian_Races_Mod_FU' is missing dependency 'FrackinUniverse'

Again that fracking universe. Lets see,  do this mod are installed or not.

**Comment by AmoraSilver** [comment]
I don't know why, but from what I can tell this mod and Frackin Universe are just simply not compatible.

**Comment by NetGlitched** [comment]
Seems to be fixed now, thanks.

**Comment by NetGlitched** [comment]
> 
> 
> I don't know why, but from what I can tell this mod and Frackin Universe are just simply not compatible.

I was trying to remove FU for that reason, however clearly I missed a couple of the mods that depended on it.
