### ISSUE TITLE
Can't get NPC preds?

### ISSUE THREAD

**Issue by Noxus42** [Sheights/StarboundSimpleVoreMod#170]
I've been trying to get some NPC predators set up, but so far no matter what sort of house I set up or badges I use for the tenants, I always get a non-digestible prey character. 

Also it seems that teleporting with a prey inside you breaks the world, either rendering you unable to return to it, or resetting it back to its original state.

**Comment by florancetheavian** [comment]
That happens to me sometimes too! The solution is simple! All you have to do is ONLY mine the COLONY DEED with your matter manipulator, then place it in the same or different spot. Also, you can get a different npc by staying in one spot after placing the colony deed, or walking away after placing it. And yes the teleporting with the prey inside you. This happens to me time to time. So before I teleport, I make sure I have no npc inside of me by double tapping the E key. Then I teleport. It also helps if you back up your game 1 every week. It takes up space on your hard drive, but it is mostly effective!

**Comment by Noxus42** [comment]
Hm, well it seems to work! Thanks!

**Comment by florancetheavian** [comment]
No prob!
