### ISSUE TITLE
Mod crashes game at start (starbound 1.4)

### ISSUE THREAD

**Issue by Eclipse8264** [Sheights/StarboundSimpleVoreMod#175]
the mod seems to need updating or fixing. it seems to be crashing my game at the fish logo, and starbound is updated to 1.4.
here is the log of the crash.
i don't get the log fully, but all the StarboundSimpleVoreMod things have Errors. i may have mist samething, but that is all i know.
[starbound.log](https://github.com/Sheights/StarboundSimpleVoreMod/files/3533731/starbound.log)

**Comment by KH007** [comment]
As far as I know, this mod has not been updated to 1.4 yet, and is still a 1.3 mod. I suggest looking around the other threads to verify.

**Comment by Eclipse8264** [comment]
> As far as I know, this mod has not been updated to 1.4 yet, and is still a 1.3 mod. I suggest looking around the other threads to verify.

*hits myself in the face*
i tryed using the new 1 wronge. i took StarboundSimpleVoreMod out of the zip and zipped it up, then used StarboundSimpleVoreMod.rar (the one i maed) and the game works.
still, thanks the help in finding the fix.
