### ISSUE TITLE
Isn't tails a minor?

### ISSUE THREAD

**Issue by Stuff12394** [Sheights/StarboundSimpleVoreMod#224]
Why does tails have AV? He's literally 8 years old

**Comment by Stuff12394** [comment]
@Sheights This could get this project banned, so hopefully it gets removed or something

**Comment by florancetheavian** [comment]
with all due respect, no one really uses him, so if you don't like it you could probably go into the files and remove him from your download yourself.

**Comment by Stuff12394** [comment]
> with all due respect, no one really uses him, so if you don't like it you could probably go into the files and remove him from your download yourself.

Alright, thanks for your input
