### ISSUE TITLE
Game won't start

### ISSUE THREAD

**Issue by SomniumOfLight** [Sheights/StarboundSimpleVoreMod#236]
So I recently downloaded the mod to try it out, but every time I try to start it the game window closes soon after it gets to the Chucklefish logo loading screen - I can't even get to the main menu.  Any idea why this is happening?  My best guess is that it's maybe mod incompatibility since I DO have a few mods installed...

**Comment by florancetheavian** [comment]
I see, that would depend on which mods you had installed previously. I know the entirety of Frackin Universe is pretty much incompatible except a handful. and I know a couple others that are not on the steam community workshop are incompatible with the mod.

would you mind sharing what mods these are that might be causing the problem?

**Comment by SomniumOfLight** [comment]
I don't have Frackin Universe - the mods I have installed are mostly custom species mods.  I've got the Draconis Race, Draconis Tenant Fix, Draconis Race Tweaks, the Avali, The Shoggoth Race Mod and Friends, The Nomadic De'nelaun, the Scyphojel, the Grecken, the Saturnians, and the Race Traits Mod.  I've also got Thermal Surge Planets and Vanilla World Variety, both planet mods, Futara's Full Bright Shader, which makes bright spots on like, clothes and stuff look like they're glowing, and of course one of the mods needed to play as custom species that I regrettably can't remember the name of - it's one with 100 race slots, though.  Do you know if any of those are incompatible?

**Comment by florancetheavian** [comment]
I see, the race mods shouldn't cause any problems, but I'm not too sure about the planet mods, like the surge one and the vanilla planet variety?

maybe those are the issue?

if that doesn't work getting rid of those feel free to reinstall them and let me know :)

**Comment by SomniumOfLight** [comment]
Ok I'll let you know if there's an issue with those mods... it could also be that I just installed the mod wrong, I double-checked the "How to Install" instructions and it looks like I may have missed a step by accident...

**Comment by florancetheavian** [comment]
I see, yeah, installing it wrong could be playing a part, I'll be here

**Comment by SomniumOfLight** [comment]
Ok so I tried reinstalling it and it actually worked this time - I'll check to see if the planet mods work because I uninstalled them earlier, but it looks like installing it wrong may have been the problem!  (I have something to do now tho so I'll do that later and let you know how it turns out!)

**Comment by SomniumOfLight** [comment]
Ok, tried all the mods I already had and they still function with the Vore mod, including the planet ones, so it was an installing-it-wrong issue instead of an incompatibility issue!  Thanks for the help even if I only needed it because I was crap at reading the instructions lol XD

**Comment by florancetheavian** [comment]
makes sense, glad it worked out!! :D
