### ISSUE TITLE
Unable to be vored

### ISSUE THREAD

**Issue by walkingbyself** [Sheights/StarboundSimpleVoreMod#47]
While using the Unofficial SSVM, Version 8.0.1 mod along with the mod EBS & EEBS, I have been unable to be eaten by NPC preds. The NPC's will do the vore animation and will do the bulging anatomy and text, but I constantly remain outside the NPC pred.

Example: http://imgur.com/Q9N3tHH

**Comment by Sheights** [comment]
You are on your ship. The NPCs use a projectile to inflict the vore status condition on you. While on your ship you are immune to projectiles. Consult the README about disabling invulnerability on your ship and allowing tenants to eat you... Or whatever it is you want to call what that one would do to you.
