### ISSUE TITLE
Access

### ISSUE THREAD

**Issue by MaxShadowland** [Sheights/StarboundSimpleVoreMod#50]
I have correctly installed the mod, due to the availability of the colony deed, I still can't seem to access the vore hall, can someone explain to me how to get there?

Thank you in advance!

**Comment by Sheights** [comment]
The colony deed is not specific to our mod, unless you mean the compact deed. Anyway, you can find the mall at the ancient gate. The same way you got to the outpost.

**Comment by MaxShadowland** [comment]
Oh well, when I go to any ancient gate I only have one destination, can you explain to me what I may have done wrong?

**Comment by MaxShadowland** [comment]
Alright I realized that there was a folder inside of the folder, so I extracted it, and now I have an option to run Starbound 32-bit, is that a good sign?

**Comment by MaxShadowland** [comment]
I also just realized I had the wrong folder for the mods

**Comment by MaxShadowland** [comment]
And now it is fixed
