### ISSUE TITLE
Crash while using this mod

### ISSUE THREAD

**Issue by PAHNKAPIE** [Sheights/StarboundSimpleVoreMod#52]
As soon as I start the game, it crashes. I have two other mods, the Avali and the Sergal mod. That and the character creation mod, all acquired from Steam Workshop. The log is attached below. 
[starbound.txt](https://github.com/Sheights/StarboundSimpleVoreMod/files/392265/starbound.txt)

**Comment by Sheights** [comment]
There is a known conflict with the sergal mod right now. Please disable it and try again.

**Comment by PAHNKAPIE** [comment]
I actually got help from a friend and went into the executable of the "sergal.chest" and "sergalchest.recipe" where the conflict seemed to arise. I just renamed the item to say "sergalchestvore" in both of those executables. So far, it seems to have fixed the problem.

**Comment by Sheights** [comment]
Yeah they keep it from crashing but now you won't be able to get sergal vore tenants. Just a heads up. You seem to understand the problem so I will close this.
