### ISSUE TITLE
Mod conflict with Sergal race mod

### ISSUE THREAD

**Issue by SpadesNeil** [Sheights/StarboundSimpleVoreMod#54]
http://steamcommunity.com/sharedfiles/filedetails/?id=731125431&tscn=1470311085

Both mods add sergal NPCs. Running these mods at the same time results in a crash. Considering this mod DOES NOT add sergals as a playable race, and how closely related sergals are to vore, this should probably be amended.

**Comment by Sheights** [comment]
All fixed in 8.1 Closing
