### ISSUE TITLE
Is not working

### ISSUE THREAD

**Issue by Tairanos** [Sheights/StarboundSimpleVoreMod#57]
I put the folder inside the mods folder (....common\Starbound\mods) when the game loads it says that the mod loaded,but actualy nothing happened

**Comment by Sheights** [comment]
You need to visit the ancient gate to access the Foodhall to gain access to all content.

**Comment by Tairanos** [comment]
Oh....gona do that,i thought that there would be a new race on the selection screen right at the begining, tanks for the assist
