### ISSUE TITLE
Outside when eaten

### ISSUE THREAD

**Issue by qpwoeir** [Sheights/StarboundSimpleVoreMod#58]
I have had a look through everything and found out that the problem is being in the ship. so I went on to a planet and it fixed it... for zoroark. anyone else, it doesn't work. I am only using UB at the moment.
quick update: zoroark has now stopped working

**Comment by qpwoeir** [comment]
turns out I had admin. not to worry.

**Comment by qpwoeir** [comment]
Lynn doesn't seem to work. I have tried everything.

**Comment by Sheights** [comment]
What is wrong with Lynn, what isn't working about her?

**Comment by qpwoeir** [comment]
I'm outside when eaten. I'm not on a ship and I'm not admin

**Comment by qpwoeir** [comment]
hmm... seems like it will work when it wants to. it is now working
