### ISSUE TITLE
C tenants dont work

### ISSUE THREAD

**Issue by qpwoeir** [Sheights/StarboundSimpleVoreMod#59]
As the title said.

**Comment by Sheights** [comment]
What doesn't work about them?

**Comment by qpwoeir** [comment]
only a normal npc spawns. not one related to this mod

**Comment by AmoraSilver** [comment]
Are you using just the C alone or with a D or V?  Using C alone does nothing as you also need the V "vore" tag or the D "digestion" tag along with it.  Certain NPCs only show with one or the other, as the pokemon Lucario will show up with a CV combo, but not a DV combo.

**Comment by qpwoeir** [comment]
ok that's working now. thanks.
