### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by Michaelcoad2** [Sheights/StarboundSimpleVoreMod#60]
a friend cant download this because there computer is saying its a virus

**Comment by AmoraSilver** [comment]
Are you downloading the zip file or tar.gz file?

**Comment by Michaelcoad2** [comment]
they tried both and they are usinig AVG, i even uploaded it to google drive and dropbox for them but they still couldnt download it

**Comment by AmoraSilver** [comment]
After some thought, I knew you were going to say AVG...

AVG is notorious for giving false positives for zip files and the like.  The best option is to simply disable AVG, download the file, unzip it into the mod folder, delete the file, then re-enable AVG.  There really is no other workaround.

**Comment by Michaelcoad2** [comment]
hes gonna try again in a bit

**Comment by Michaelcoad2** [comment]
he has a second antivirus blocking it

**Comment by AmoraSilver** [comment]
Why in hell would you use 2 antivirus programs on one computer?!?

Also, I don't know what to tell you, I know for a fact the files are not viruses or contain viruses.  If he's being this overly cautious despite the simple fact they are not, he's just not going to enjoy using this mod.

**Comment by Michaelcoad2** [comment]
well his second antivirus is malware bytes and he tried a older version and enjoyed it

**Comment by AmoraSilver** [comment]
Well, I don't know what is going on then since I use malwarebytes myself and am not getting any virus notification from the files.  I even scanned the entire unzipped mod folder.  And yes my program is up to date.

**Comment by Michaelcoad2** [comment]
well, hes trying everything so... no response just yet

**Comment by Michaelcoad2** [comment]
hes got it

**Comment by AmoraSilver** [comment]
Alright, if it's working this can be closed.
