### ISSUE TITLE
Fenerox tenant not working

### ISSUE THREAD

**Issue by Brokhart** [Sheights/StarboundSimpleVoreMod#64]
I've tried repeatedly to spawn the Fenerox Vore Tenant, but it isn't working. they spawn in and immediately die, getting trapped in an infinite loop.

This also happens with the Digest vore Fenerox Tenant. Anyone know what causes this?

**Comment by AmoraSilver** [comment]
Okay, I have the same issue it seems, but do not know the direct cause of it.  I'm going to message Sheights directly to let them know of this bug.  Leave this issue open for now.

**Comment by Brokhart** [comment]
Alright, Will do.

I've only got Xbawks and the SSVM installed, so it's likely not a mod conflict. I've also noticed that it's extremely hard to even trigger the fenerox vore tenant spawn; If i have anything other than a dusty table and 1~2 primative doors i get a centaur of some kind. Maybe it's a tenant spawn conflict?

**Comment by AmoraSilver** [comment]
Yeah if the fenerox tag is 12 or higher, a zebra centaur spawns instead.  
Sheights has already messaged back and is now looking into it.

**Comment by Brokhart** [comment]
Alright. Thanks for helping!

**Comment by Brokhart** [comment]
Just gonna leave this here, Fenerox Tenant has been fixed as of the most recent version.
