### ISSUE TITLE
FoodHall Mall not showing up

### ISSUE THREAD

**Issue by Apparit** [Sheights/StarboundSimpleVoreMod#69]
I recently updated this mod from Version 8.0.3 to Version 8.5.0. And now the Food Hall is not showing up on the teleporter list. I did follow the updating instructions. Items from the mod still spawn as well, I even used some spawn item codes to spawn the portable bellybound store and it had all the new items. How do I go about fixing this? I would really like access to the FoodHall.

**Comment by AmoraSilver** [comment]
Use the teleporter at the 2-stop teleport shop, it should be there.  Right after, go use the teleporter in the food hall to save it to your teleport list.

**Comment by Apparit** [comment]
That fixed it! Thanks!
