### ISSUE TITLE
Tea Spot Rodent Predator Broken

### ISSUE THREAD

**Issue by Brokhart** [Sheights/StarboundSimpleVoreMod#74]
The "Tea Spot" Predator tenant is unable to devour me or other npcs. It fires the vore projectile and grows a gut, but nothing actually gets eaten.

**Comment by AmoraSilver** [comment]
Are you on the ship or have admin active?

**Comment by Brokhart** [comment]
Nope

**Comment by AmoraSilver** [comment]
Hmm, I'll have to look into this then.  It takes a bit for my game to boot up, too many mods.

**Comment by Brokhart** [comment]
Yeah, it was really weird. I'll close the issue for now. I seem to be bumping into loads of issues today.
