### ISSUE TITLE
Make an NPC eat more often?

### ISSUE THREAD

**Issue by Xero256** [Sheights/StarboundSimpleVoreMod#97]
This primarily applies to NPC's that can eat more than one person. Is there any way to make them eat more - NPC's or otherwise. Example:  Victor. Like most residents, he likes to loaf about here and there. This is fine. However, he'll munch someone and then continue about his business. Supposedly, he'll chow down on up to 4 people. Never seen him nom more than 2. Managed to catch him around that time and I offered to be a 3rd. After much refusal (more on that in a moment) he munched my character as well.

When trying to offer to be nommed, he'll frequently turn his nose up and respond as if you are prey that he has already eaten and yet you totally haven't. I have seen this with other predators too. They simply can't be bothered to munch, even if it is offered to them by a player character. Is this a personality trait?

Can you make the NPC more hungry?

Also, paint me jealous.... Victor is a Hibani and could, should he feel up to it, loaf about with 4 people in his belly. My character, also a Hibani, can only nom one.

--Xero

**Comment by Sheights** [comment]
The eating algorithm changes in 8.6.0 It should allow more frequent eating in crowded spaces. You can re make this issue after 8.6 when the new methods are implemented and you can see if it's more to your liking.
